### ISSUE TITLE
Crash when Piston activated

### ISSUE THREAD

**Issue by TheirOwn** [MSandro/sky_fabrication2#14]
https://crashy.net/iFCx6OzNt8t1ri6PPVdS

This happens both in single player and on my server

**Comment by MSandro** [comment]
Thank you. 
I'll take a close look at this in the coming days. The next update (1.1.0) will come next Friday at the latest. I hope that I can quickly find the cause of these many NullPointerExceptions.

**Comment by MSandro** [comment]
This is an very critical bug, I was able to reproduce it. In my current Dev Environment for v1.1.0 the issue seems to be fixed with an mod update. I will try to release it as soon as possible, hopefully on monday. I want to hurry up with the update because I don't want to have to start my server 10 times every day.

**Comment by MSandro** [comment]
fixed in 1.0.2
